### ISSUE TITLE
getting error while adding http-transformer

### ISSUE THREAD

**Issue by DileepDivakaran** [mulesoft/docs-api-manager#134]
Is this http-transformer available only on enterprise users.
I am trying to use the same, API Gateway HTTP Policy transform extension but not able to resolve the dependency, whenever i am trying to add the dependency, i am getting error as 
Could not resolve dependencies for project d679fd1c-6417-470f-aebb-7079aef6d6f1:dileepd:mule-policy:1.0.0-SNAPSHOT: Failure to find 68ef9520-24e9-4cf2-b2f5-620025690913:mule-http-policy-transform-extension:jar:mule-plugin:3.0.0 
<dependency>
        <groupId>68ef9520-24e9-4cf2-b2f5-620025690913</groupId>
  <artifactId>mule-http-policy-transform-extension</artifactId>
  <version>3.0.0</version>
  <classifier>mule-plugin</classifier>

If i didnt add this dependency in pom.xml , i am getting error while attaching the api as 
org.xml.sax.SAXParseException; lineNumber: 13; columnNumber: 81; cvc-complex-type.2.4.a: Invalid content was found starting with element 'http-transform:set-response'. One of '{"http://www.mulesoft.org/schema/mule/core":abstract-message-processor, "http://www.mulesoft.org/schema/mule/core":abstract-mixed-content-message-processor}' is expected.

**Comment by chris-campbell9** [comment]
I'm a little confused - I'm thinking this isn't a documentation bug. If it is, can you link to the page where the bug resides?
