### ISSUE TITLE
Repeated entries in "Default Policies Directory"

### ISSUE THREAD

**Issue by pszuster** [mulesoft/docs-api-manager#228]
In the Default Policies Directory section(https://docs.mulesoft.com/api-manager/2.x/policies-ootb-landing-page) there are two redundant entries:

- **Throttling and Rate Limiting**: https://docs.mulesoft.com/api-manager/2.x/throttling-rate-limit-concept****
- **Rate Limiting and Throttling**: https://docs.mulesoft.com/api-manager/2.x/rate-limiting-and-throttling

**Comment by Mulesoft-Mysti** [comment]
Thank you for mentioning this. The team has been alerted.

**Comment by chris-campbell9** [comment]
Fixed in the following PR:
https://github.com/mulesoft/docs-api-manager/pull/300
