### ISSUE TITLE
Broken link to the code repository

### ISSUE THREAD

**Issue by vasanth-srg** [mulesoft/docs-api-manager#352]
Hi,
I was going through "custom-response-policy-example.adoc" and found a broken link to the code repository:
https://github.com/mulesoft/api-gateway-custom-policies-examples

I would like to know proper repository link.

Thanks

**Comment by chris-campbell9** [comment]
Hello,

Thanks so much for bringing this to our attention. Unfortunately, the linked GitHub repository is no longer public, and another repository hasn't been made available.

I'll submit a documentation PR that removes the line containing the broken link.

Thank you again.

Regards,
Chris Campbell
