### ISSUE TITLE
Managing Applications > https://docs.mulesoft.com/api-manager/2.x/defining-sla-tiers

### ISSUE THREAD

**Issue by cowa1986** [mulesoft/docs-api-manager#417]
"If you set the tiers for manual approval, email notifications are sent to you when developers request access for their applications. You can review the applications on the API version details page and approve, reject, or revoke requests. If a developer asks to change tiers, you can also review the change request and approve the application for the new tier or reject the change request."

Can one specify who is "you" specific userrole and with what permission? For instance a access approver not espacially a platform admin, also wants to grant access for access requesters in a prd environment.

**Comment by chris-campbell9** [comment]
Hi @cowa1986, thanks for reporting this! We'll take a look ASAP.

**Comment by bjoson-mulesoft** [comment]
@cowa1986, you can approve requests if you have the Organization Administrators role or if you have the API Manager permission API Manager Environment Administrator or Manage Contracts.
 
I will update the documentation with this information.

**Comment by bjoson-mulesoft** [comment]
@cowa1986, I have added a cross-reference to "Approve or Reject Access Requests" to the See Also section. This page gives details about required permissions in the Prerequisites section. 
This Issue is resolved by the following PR:
https://github.com/mulesoft/docs-api-manager/pull/420

**Comment by cowa1986** [comment]
Dear Beth,

Thank you very much!

K.r. Coen

Op di 21 dec. 2021 02:44 schreef Beth Joson ***@***.***>:
